sudo: false
language: node_js

node_js:
  - 8
  - 10
  - node

install:
  - npm install
  - npm install https://github.com/Microsoft/definitelytyped-header-parser

before_script:
  - npm run build
  - npm run yaml

script:
  - npm test
