sudo: false
language: node_js

node_js:
  - 6
  - 8
  - node

install:
  - npm install
  - npm install https://github.com/Microsoft/definitelytyped-header-parser

before_script:
  - npm run build

script:
  - npm test
